import Head from "next/head";
import styles from "@/styles/Home.module.css";
import { MdOutlineDarkMode } from 'react-icons/md'
import Navbar from "@/components/Navbar/Navbar";
import Header from "@/components/Header/Header";



export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <Navbar />
        <Header />
      </main>
    </>
  );
}
