import Head from "next/head";

export function Layout({ children }) {
  return (
    <>
      <Head>
        <title>Kleber AI</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        {children}
      </div>
    </>
  );
}
